title: Srijit Paul
description: Maryland Center for Fundamental Physics, College Park, USA
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
